-- SUPABASE FIXES FOR MISSING TABLES & POLICIES

-- 1. Create quotations table if missing
CREATE TABLE IF NOT EXISTS public.quotations (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users NOT NULL,
    customer_name text,
    date timestamp with time zone,
    data jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for quotations
ALTER TABLE public.quotations ENABLE ROW LEVEL SECURITY;

-- Policies for quotations
DROP POLICY IF EXISTS "Users can insert their own quotations" ON public.quotations;
DROP POLICY IF EXISTS "Users can view their own quotations" ON public.quotations;
DROP POLICY IF EXISTS "Users can update their own quotations" ON public.quotations;
DROP POLICY IF EXISTS "Users can delete their own quotations" ON public.quotations;

CREATE POLICY "Users can insert their own quotations"
ON public.quotations FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own quotations"
ON public.quotations FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own quotations"
ON public.quotations FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own quotations"
ON public.quotations FOR DELETE
TO authenticated
USING (auth.uid() = user_id);


-- 2. Create admin_analytics table if missing
CREATE TABLE IF NOT EXISTS public.admin_analytics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    details jsonb,
    user_id uuid REFERENCES auth.users,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for admin_analytics
ALTER TABLE public.admin_analytics ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to log activity
DROP POLICY IF EXISTS "Allow authenticated insert to admin_analytics" ON public.admin_analytics;
CREATE POLICY "Allow authenticated insert to admin_analytics"
ON public.admin_analytics FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policy to allow admins to view analytics
-- Note: Replace 'admin@example.com' with your actual admin email if known
DROP POLICY IF EXISTS "Allow admins to view admin_analytics" ON public.admin_analytics;
CREATE POLICY "Allow admins to view admin_analytics"
ON public.admin_analytics FOR SELECT
TO authenticated
USING (auth.jwt() ->> 'role' = 'service_role' OR auth.jwt() ->> 'email' IN (SELECT email FROM public.profiles WHERE settings->>'role' = 'admin'));

-- 3. Ensure trips table has all necessary columns for synchronization
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS customer_name text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS pickup_location text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS drop_location text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS distance numeric;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS amount numeric;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS date timestamp with time zone;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS details jsonb;
