-- Create the table for tracking route searches
create table public.route_searches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pickup_location text not null,
  drop_location text not null,
  trip_type text not null,
  vehicle_type text not null,
  distance_km numeric,
  estimated_fare numeric
);

-- Add some security policies (RLS)
alter table public.route_searches enable row level security;

-- Allow anyone (anon) to insert searches (since we want to track public usage)
create policy "Allow anon insert"
on public.route_searches
for insert
to anon
with check (true);

-- Allow anyone to read searches (for trending display)
create policy "Allow anon select"
on public.route_searches
for select
to anon
using (true);
