-- ============================================================
-- Sarathi Book — Payments & Subscription Migration (v2)
-- Fully idempotent — safe to re-run multiple times
-- Run this in Supabase Dashboard → SQL Editor
-- ============================================================

-- Step 1: Add plan tracking columns to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS plan_expires_at timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS payment_id text;

-- Step 2: Drop and recreate payments table cleanly
-- (safe to re-run — drops any partial table from a failed first run)
DROP TABLE IF EXISTS public.payments CASCADE;

CREATE TABLE public.payments (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamptz DEFAULT now() NOT NULL,
    user_id       uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    payment_id    text NOT NULL,
    order_id      text,
    plan          text NOT NULL,
    billing_cycle text DEFAULT 'monthly',
    amount_paise  integer NOT NULL,
    status        text NOT NULL DEFAULT 'pending',
    captured_at   timestamptz
);

-- Step 3: Enable RLS
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Step 4: Policies (DROP first so re-run doesn't fail)
DROP POLICY IF EXISTS "Users see own payments" ON public.payments;
CREATE POLICY "Users see own payments"
    ON public.payments FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Service role manages payments" ON public.payments;
CREATE POLICY "Service role manages payments"
    ON public.payments FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Step 5: Indexes
CREATE INDEX IF NOT EXISTS payments_user_id_idx  ON public.payments(user_id);
CREATE INDEX IF NOT EXISTS payments_payment_idx   ON public.payments(payment_id);

-- ✅ Verification — run these to confirm success
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'profiles'
  AND column_name IN ('plan_expires_at', 'payment_id', 'settings')
ORDER BY column_name;

SELECT COUNT(*) AS payment_records FROM public.payments;
