-- Add a readable, auto-incrementing driver code to profiles
-- This code is easier for humans to remember than the UUID
-- It starts at 10001 to look professional

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS driver_code INT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001);

-- Note: The column is added to the table. Existing rows will automatically get values if they don't have them (though for IDENTITY column, backfilling existing rows depends on exact postgres version/command behavior). 
-- In recent Postgres, adding an identity column to a table with data *does* populate it. 
-- However, just in case, we can force update nulls if needed, but usually unnecessary.
